# Определение версии Docker Compose и начало описания сервисов
version: '3.3'

services:
  backend:
    # Сборка образа для сервиса django из текущей директории
    build: .
    
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python3 main.py
    volumes:
     - .:/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 11702:11702
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgres:14
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=sesh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    expose:
      - "3306"
  
  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "silaeder_dairy@admin.org"
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - "11704:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdbdata: null
  pgadmin: null
