# Определение версии Docker Compose и начало описания сервисов
version: '3.3'

services:
  backend:
    # Сборка образа для сервиса django из текущей директории
    build: .
    
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python3 main.py
    volumes:
     - .:/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 11802:11802
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgres
    ports:
      - 5435:5432
    # Задание переменных окружения для контейнера с postgres
    environment:
      PGDATABASE: "diarydb"
      POSTGRES_DB: "diarydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
      PGPASSWORD: "1"
      PGUSER: "postgres"
      PG_TRUST_LOCALNET: "true"
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - ./pgdbdata:/var/lib/postgresql/data/
    expose:
      - "5435"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "silaeder_dairy@admin.org"
      PGADMIN_DEFAULT_PASSWORD: "1"
    ports:
      - "11804:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdbdata: null
  pgadmin: null
